name: OWASP ZAP Integration with GitHub Action-Basic
on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the webapplication
    steps:
      steps:
    - name: ZAP Scan
       uses: zaproxy/action-full-scan@v0.4.0
       with:
       target: 'https://www.zaproxy.org/'